// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-uJFjlHUmaltr2Fw71mWB_O241T8OkHw',
    appId: '1:922953041691:web:1732ece7472a3cc901f5be',
    messagingSenderId: '922953041691',
    projectId: 'smart-attendance-system-64bf9',
    authDomain: 'smart-attendance-system-64bf9.firebaseapp.com',
    databaseURL: 'https://smart-attendance-system-64bf9-default-rtdb.firebaseio.com',
    storageBucket: 'smart-attendance-system-64bf9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj1lWdaK8xGSwTl2oHNVhUDyAXerXXDLE',
    appId: '1:922953041691:android:3af4b0d5d590423c01f5be',
    messagingSenderId: '922953041691',
    projectId: 'smart-attendance-system-64bf9',
    databaseURL: 'https://smart-attendance-system-64bf9-default-rtdb.firebaseio.com',
    storageBucket: 'smart-attendance-system-64bf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABFNB5cKTJ7KUKRvfGNbs3JJ8Lml1PGHg',
    appId: '1:922953041691:ios:d59ad465721be6a601f5be',
    messagingSenderId: '922953041691',
    projectId: 'smart-attendance-system-64bf9',
    databaseURL: 'https://smart-attendance-system-64bf9-default-rtdb.firebaseio.com',
    storageBucket: 'smart-attendance-system-64bf9.appspot.com',
    iosClientId: '922953041691-tvoud1ps75ls9igke13r3pcrk1075a98.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAttendanceSystem',
  );
}
